comment: false

coverage:
  status:
    project:
      default:
        threshold: 5% # allow project coverage to drop by 5% before failing CI checks
    patch:
      default:
        target: 0% # test coverage is not required for a pull request

